### ISSUE TITLE
not working with 2fa?

### ISSUE THREAD

**Issue by m52go** [uraway/electron-oauth-twitter#9]
hi folks -- i'm assuming i'm doing something stupid since no one else seems to have this issue.

i can't get 2fa to work. i've successfully tried non-2fa logins from multiple accounts, but can't get 2fa logins to work. 

upon entering the password and clicking submit: the login window doesn't seem to do anything, but the console clears, and i get an sms with the login code (but can't enter it anywhere).

i also tried setting an app password but get the same behavior...which is weird because if i immediately switch to an account with no 2fa in the same login window, it works again.

has anyone experienced this?

**Comment by uraway** [comment]
Hi, thank you for your comment. actually i have never used 2fa with twitter. Give me some to investigate the problem.

**Comment by uraway** [comment]
Hi, @m52go. I just published electron-oauth-twitter v1.2.0 coped with 2fa via sms. Can you try it out?

But still i have never tried 3rd-party lib for 2fa with twitter.

**Comment by m52go** [comment]
@uraway it works!!! i tested with both 2fa and non-2fa accounts and it worked like a charm.

thank you a TON :D
